apiVersion: apps/v1
kind: Deployment
metadata:
  name: d-nagp-app-ui
  labels:
    app: nagp-app-ui
    type: ui
    stack: nagp-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nagp-app-ui
      stack: nagp-app
  template:
    metadata:
      labels:
        app: nagp-app-ui
        type: ui
        stack: nagp-app
    spec:
      containers:
        - name: nagp-app-ui
          image: {{ .Values.images.ui }}:{{ .Values.imgVersion }}
          ports:
            - name: http
              containerPort: 3000
          env:
            - name: API_BASE_URL
              value: {{ .Values.apiBaseUrl }}
          resources:
            requests:
              cpu: 250m
              memory: 500Mi
            limits:
              cpu: 500m
              memory: 1Gi